#!/system/bin/bash
# This is an example config.
# Edit it and place it as /sdcard/.cr/config.d/crName where crName is the name you give to this file to describe it.

crDescription="An example config."

# You need to specify either a rootPartition or rootImage.
#   rootPartition is a normal partition containing your chroot environment.
#   rootImage is an image of a partition. Ie there is no partition table.
# NOTE that this script does not yet support disk images that contain a partition table.
# rootPartition="/dev/block/sdg2"
rootPartition=""
rootImage="/sdcard/images/droid4.img"

vncNumber=1
vncResolution="3200x1800"
