#!/system/bin/bash
# Where default settings should be. You probably won't need to change this file, But these settings are abstracted out so you can if you want to.


# These are the extra file systems that you want to make available inside the chroot environment. The complexity comes in that some of them need to be done in a particular order.
# This is probably what you'll want to change.
extraMountDirs="sys proc sdcard data"

# These are the final variables defining what gets un/mounted, and in what order. If you need to nest filesystems, look at the relationship between dev and dev/pts.
extraMounts="$extraMountDirs dev dev/pts"
extraUnmounts="$extraMountDirs dev/pts dev"
