#!/system/bin/bash
# Discover new files/devices on the fly for a given directory.
# Syntax
# $0 [directoryToMonitor] [tempDirectory]


# Interpret parameters if there are any.
directoryToMonitor=${1:-/dev/block}
tempDirectory=${2:-/sdcard/tmp/nf}

# Make sure our temp directory exists.
mkdir -p "$tempDirectory"

# Get initial state.
cd "$directoryToMonitor"
ls -1 | sort -u > "$tempDirectory/$$-before"

# Compare state every 1 second.
while sleep 1;do
  clear
  date
  ls -1 | sort -u > "$tempDirectory/$$-during"
  
  diff "$tempDirectory/$$-before" "$tempDirectory/$$-during"
done
